#!/usr/bin/expect -f
# Copyright (C) 2020-2024 Dave Slotter, W3DJS (original HamPi); (C) 2026 Mike Miller, KD9QHQ (HamPi64 fork).
# SPDX-License-Identifier: GPL-3.0-or-later

set timeout 120
match_max 100000

spawn ./SDRplay_RSP_API-Linux-2.13.1.run

expect {
        -- "--More--" {
                send -- " "
                exp_continue
        }

        "\[y/n\] " {
                send -- "y\r"
                exp_continue
        }
}
